Fix stopping on prepare failing
It seems that set -eu doesn’t work the same on bash on windows than
ubuntu. Check then the environment variable content.

Co-authored-by: Jean-Baptiste Lallement <jean-baptiste@ubuntu.com>

diff --git a/.github/workflows/build-wsl.yaml b/.github/workflows/build-wsl.yaml
--- a/.github/workflows/build-wsl.yaml
+++ b/.github/workflows/build-wsl.yaml
@@ -95,7 +95,12 @@ jobs:
           cd wsl-builder/prepare-build
           go build .
           cd ../../
-          echo "AppxBundlePlatforms=$(./wsl-builder/prepare-build/prepare-build prepare ${{ env.artifactsPath }} ${{ matrix.WslID }} ${{ matrix.Rootfses }} --no-checksum)" >> $GITHUB_ENV
+          platforms="$(./wsl-builder/prepare-build/prepare-build prepare ${{ env.artifactsPath }} ${{ matrix.WslID }} ${{ matrix.Rootfses }} --no-checksum)"
+          if [ -z "${platforms}" ]; then
+            echo "ERROR: preparing build failed"
+            exit 1
+          fi
+          echo "AppxBundlePlatforms=${platforms}" >> $GITHUB_ENV
 
           # Prepare remaining env variables for msbuild
           buildMode="SideloadOnly"
